[INFO] [02:08:07] [MainThread] - СКРИПТ ЗАПУЩЕН!
[WARNING] [02:08:13] [Thread-1 (warp1)] - Не могу найти фиолетовый! Пролистываю.....
[WARNING] [02:08:21] [Thread-1 (warp1)] - Зеленый не найден! Перепроверяю........
[WARNING] [02:08:24] [Thread-7 (warp1)] - Не могу найти фиолетовый! Пролистываю.....
[WARNING] [02:08:42] [Thread-7 (warp1)] - Зеленый не найден! Перепроверяю........
[INFO] [02:08:44] [Thread-7 (warp1)] - Перепроверка неуспешна! Выключаю таймер и выставляю статус dock = 1
[INFO] [02:08:47] [Thread-7 (warp1)] - Запускаем функцию варпа!
[INFO] [02:09:59] [Thread-7 (warp1)] - Запускаем функцию разгрузки карго!
[INFO] [02:10:40] [Thread-7 (warp1)] - Запускаем функцию андока!
[ERROR] [02:10:40] [Thread-7 (warp1)] - An error has been caught in function 'run', process 'MainProcess' (11404), thread 'Thread-7 (warp1)' (14432):
Traceback (most recent call last):

  File "C:\Users\denis\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 995, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002130518B240>
    └ <Thread(Thread-7 (warp1), started 14432)>
  File "C:\Users\denis\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002130518AF20>
    └ <Thread(Thread-7 (warp1), started 14432)>
> File "C:\Users\denis\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-7 (warp1), started 14432)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-7 (warp1), started 14432)>
    │    └ <function warp1 at 0x000002131EEC0B80>
    └ <Thread(Thread-7 (warp1), started 14432)>

  File "d:\covetor\avto_telegram2.py", line 60, in warp1
    functions.undock()                        # Андокаемся
    │         └ <function undock at 0x000002131EEAF060>
    └ <module 'functions' from 'd:\\covetor\\functions.py'>

  File "d:\covetor\functions.py", line 86, in undock
    pyautogui.moveTo(341+RND(-30, 10),465+RND(-10,30))
    │         └ <function moveTo at 0x000002131E9813A0>
    └ <module 'pyautogui' from 'C:\\Users\\denis\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pyautogui\\__ini...

UnboundLocalError: cannot access local variable 'RND' where it is not associated with a value
